name: test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        containers:
        - 1.18.10-bullseye
        - 1.19.5-bullseye
        - 1.20.rc3-bullseye
    runs-on: ubuntu-latest
    container: golang:${{ matrix.containers }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.containers }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.containers }}-go-
      - name: Unit Tests
        env:
          IPFS_URL: ${{secrets.IPFS_URL }}
        run: go test -race -timeout=60s ./...
